(() => {
  "use strict";
  const cfg = window.LQ_CONFIG;
  const $ = (s, root=document) => root.querySelector(s);
  const $$ = (s, root=document) => [...root.querySelectorAll(s)];
  const esc = v => String(v ?? "").replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
  const wa = message => `https://wa.me/${cfg.WHATSAPP_NUMBER}?text=${encodeURIComponent(message)}`;
  const money = v => `${cfg.CURRENCY}${esc(v || "Price on enquiry")}`;

  function shell(){
    const h=$("#site-header"), f=$("#site-footer");
    if(h) h.innerHTML=`<header class="site-header"><a class="brand" href="index.html"><span class="brand-mark">LQ</span><span><strong>Luna Quilling</strong><small>Handmade paper art</small></span></a><button class="menu-toggle" aria-label="Open menu" aria-expanded="false">☰</button><nav class="nav"><a href="index.html">Home</a><a href="works.html">Our Works</a><a href="custom.html">Custom Artwork</a><a href="about.html">About</a><a href="contact.html">Contact</a></nav></header>`;
    if(f) f.innerHTML=`<footer class="footer"><div><a class="brand" href="index.html"><span class="brand-mark">LQ</span><span><strong>Luna Quilling</strong><small>Handmade paper art by Rathana</small></span></a><p>Handmade quilling artwork, personalised with care. Delivery across India.</p></div><div class="footer-links"><a href="works.html">Our Works</a><a href="custom.html">Custom Artwork</a><a href="https://www.instagram.com/lunaquilling/" target="_blank" rel="noopener">Instagram</a><a href="${wa('Hello Rathana, I would like to enquire about Luna Quilling artwork.')}" target="_blank" rel="noopener">WhatsApp</a></div><small>© ${new Date().getFullYear()} Luna Quilling</small></footer>`;
    const t=$(".menu-toggle"), n=$(".nav"); t?.addEventListener("click",()=>{const open=n.classList.toggle("open");t.setAttribute("aria-expanded",open)});
  }
  async function apiGet(action,params={}){ if(!cfg.API_URL || cfg.API_URL.includes("PASTE_")) throw Error("Apps Script API URL is not configured."); const u=new URL(cfg.API_URL);u.searchParams.set("action",action);Object.entries(params).forEach(([k,v])=>v!==undefined&&v!==""&&u.searchParams.set(k,v));const r=await fetch(u,{cache:"no-store"});if(!r.ok)throw Error("API request failed");return r.json(); }
  function card(w){ const img=w.imageUrl||cfg.PLACEHOLDER_IMAGE; return `<article class="art-card"><a class="art-image" href="artwork.html?workId=${encodeURIComponent(w.workId)}"><img loading="lazy" src="${esc(img)}" alt="${esc(w.title)}" onerror="this.onerror=null;this.src='${cfg.PLACEHOLDER_IMAGE}'"></a><div class="art-body"><span class="tag">${esc(w.category)}</span><h3>${esc(w.title)}</h3><p>${esc(w.description)}</p><div class="art-bottom"><strong>Starting ${money(w.startingPrice)}</strong><a class="btn btn-small btn-secondary" href="enquire.html?workId=${encodeURIComponent(w.workId)}">Enquire</a></div></div></article>`; }
  async function loadWorks(){ const target=$("#catalogue-grid")||$("#featured-grid");if(!target)return;try{const d=await apiGet("works");let works=d.works||[];if($("#featured-grid"))works=works.filter(w=>w.featured).slice(0,6);const cats=[...new Set((d.works||[]).map(w=>w.category).filter(Boolean))].sort();const sel=$("#category-filter");if(sel)cats.forEach(c=>sel.insertAdjacentHTML("beforeend",`<option value="${esc(c)}">${esc(c)}</option>`));const render=()=>{let a=works,q=$("#search-input")?.value.toLowerCase().trim(),c=sel?.value||"";if(q)a=a.filter(w=>`${w.title} ${w.category} ${w.description}`.toLowerCase().includes(q));if(c)a=a.filter(w=>w.category===c);target.innerHTML=a.length?a.map(card).join(""):`<div class="empty">No artworks match your search.</div>`};$("#search-input")?.addEventListener("input",render);sel?.addEventListener("change",render);render()}catch(e){target.innerHTML=`<div class="empty">The catalogue is temporarily unavailable. Please try WhatsApp or email us directly.</div>`;console.error(e)}}
  async function loadArtworkDetail(){const root=$("#artwork-detail");if(!root)return;const id=new URLSearchParams(location.search).get("workId");if(!id){root.innerHTML='<div class="empty">Artwork not found.</div>';return}try{const d=await apiGet("work",{workId:id});if(!d.work)throw Error();const w=d.work;root.innerHTML=`<div class="story"><div><img style="width:100%;border-radius:24px;aspect-ratio:1;object-fit:cover;background:#eee" src="${esc(w.imageUrl||cfg.PLACEHOLDER_IMAGE)}" alt="${esc(w.title)}" onerror="this.onerror=null;this.src='${cfg.PLACEHOLDER_IMAGE}'"></div><div><span class="tag">${esc(w.category)}</span><h1>${esc(w.title)}</h1><p class="lead">${esc(w.description)}</p><h3>Starting ${money(w.startingPrice)}</h3><div class="actions"><a class="btn btn-primary" href="enquire.html?workId=${encodeURIComponent(w.workId)}">Enquire about this artwork</a><a class="btn btn-secondary" target="_blank" rel="noopener" href="${wa(`Hello Rathana, I would like to enquire about "${w.title}" (Work ID: ${w.workId}).`)}">WhatsApp</a></div></div></div>`}catch(e){root.innerHTML='<div class="empty">We could not load this artwork. Please return to the catalogue.</div>'}}
  function status(el,msg,type=""){el.textContent=msg;el.className=`form-status ${type}`}
  async function file64(file,max=5*1024*1024){if(!file)return null;if(file.size>max)throw Error(`Please choose an image smaller than ${Math.round(max/1024/1024)} MB.`);return new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res({name:file.name,mimeType:file.type,data:r.result.split(',')[1]});r.onerror=()=>rej(Error('Could not read image'));r.readAsDataURL(file)})}
  async function submitForm(form,out){try{const data=Object.fromEntries(new FormData(form).entries());const file=form.elements.referenceImage?.files?.[0];data.referenceImage=await file64(file);data.action='submitEnquiry';delete data.website;const body=new URLSearchParams();for(const [k,v] of Object.entries(data))body.set(k,typeof v==='object'&&v!==null?JSON.stringify(v):String(v??''));status(out,'Sending your enquiry…');const r=await fetch(cfg.API_URL,{method:'POST',body});const d=await r.json();if(!d.ok)throw Error(d.error||'Submission failed');form.reset();status(out,`Thank you! Your enquiry ${d.enquiryId} has been received. Rathana will contact you shortly.`,'success')}catch(e){console.error(e);status(out,e.message||'We could not send the enquiry. Please use WhatsApp instead.','error')}}
  function enquirySetup(){const form=$("#artwork-enquiry-form");if(!form)return;const id=new URLSearchParams(location.search).get('workId'),sel=$("#selected-artwork");apiGet('works').then(d=>{(d.works||[]).forEach(w=>sel.insertAdjacentHTML('beforeend',`<option value="${esc(w.workId)}">${esc(w.title)} — Starting ${money(w.startingPrice)}</option>`));if(id)sel.value=id}).catch(()=>{});form.addEventListener('submit',e=>{e.preventDefault();submitForm(form,$('#artwork-status'))})}
  function customSetup(){const f=$("#custom-form");if(f)f.addEventListener('submit',e=>{e.preventDefault();submitForm(f,$('#custom-status'))})}
  document.addEventListener('DOMContentLoaded',()=>{shell();loadWorks();loadArtworkDetail();enquirySetup();customSetup();});
})();
